### ISSUE TITLE
Does this work with React Native?

### ISSUE THREAD

**Issue by yalamber** [TomPrograms/stormdb#10]
Will this work with react native?

**Comment by TomPrograms** [comment]
No it currently will not, as the engines either use `fs.writeFile`/`fs.writeFileSync` (localFileEngine) or LocalStorage (browserEngine) for storing the database, neither of which I believe are supported in react native. However, you could write your own engine, with the same method names, that uses a storage method supported in React Native. This could possibly be an expansion I make it the future.
