### ISSUE TITLE
StormDB.localFileEngine is not a constructor ??

### ISSUE THREAD

**Issue by kingstonelibrary** [TomPrograms/stormdb#12]
regarding to "Usage" in ReadMe.md
I just tried sample code in it, but encountered the above error.
const engine = new StormDB.localFileEngine("./db.stormdb");

Local storage sample(BrowserEngine) works very well ... , but
const engine = new BrowserEngine("db");

**Comment by TomPrograms** [comment]
@kingstonelibrary Are you using Javascript or Typescript?

**Comment by kingstonelibrary** [comment]
thanks
I just changed the initializing part of  in docs/web/index.js from upper code to under side one, which is in zip file  downloaded from this repo.

const engine = new BrowserEngine("db");   // works well
↓
const engine = StormDB.localFileEngine("./db.stormdb");  // Error! "StormDB.localFileEngine is not a function"

I' sure StormDB is surely loaded, but it doesn't seem to have  'localFileEngine'...
maybe I have to adjust other part of index.js, don' t  I　?

**Comment by TomPrograms** [comment]
If you are using this on the web, localFileEngine can’t be used, as it is only for local environment and wouldn’t work in the browser. If you want to use the localFileEngine use the code from the GitHub or from NPM.

**Comment by kingstonelibrary** [comment]
I thought you might make it possible to create JSON file in Browser environment by blob or something, and that's why I tried.
thanks a lot, anyway
