### ISSUE TITLE
BrowserEngine Error

### ISSUE THREAD

**Issue by fredcox** [TomPrograms/stormdb#13]
Hi, 

I write the following code with stormdb
`import { BrowserEngine, StormDB } from "stormdb";

console.log('Criando DB');
const engine = new BrowserEngine("db");
const db = new StormDB(engine);
`

And i get the following error. 

`TypeError: stormdb__WEBPACK_IMPORTED_MODULE_2__.BrowserEngine is not a constructor
Conteudo.criarDb`

**Comment by iarkaroy** [comment]
From https://github.com/TomPrograms/stormdb/blob/master/index.js, it seems you need to import `browserEngine`, not `BrowserEngine`. Have a try :)
