### ISSUE TITLE
how to delete a child property？i need delete the name in : {"next":{"name":"timi","age":40}}

### ISSUE THREAD

**Issue by exe19890522** [TomPrograms/stormdb#14]
if db is this ::  {"next":{"name":"timi","age":40}} 
i want to delete the name,how can to do??
i use this:  db.delete('next.name'); 
but it failed.

**Comment by TomPrograms** [comment]
Hello, sorry for the delayed reply. We currently don't support property accessors in the form "a.b.c" at the moment, although I am considering adding such support. For now you can accomplish your task with:

```
db.get("next").get("name").delete()
```
