### ISSUE TITLE
maybe can write data to db.stormdb file with js format?

### ISSUE THREAD

**Issue by exe19890522** [TomPrograms/stormdb#15]
in my think this one is better:
{
	"users": [{
			"name": "tom",
			"age": 20
		}, {
			"name": "lily",
			"age": 15
		}, {
			"name": "lucy",
			"age": 12
		}
	],
	"map": [],
	"ver": 7,
	"type": 1,
	"des": "tyuuu",
	"next": {
		"name": "timi",
		"age": 40
	}
}
===============
not only one line like : {"users":[....], ...................}

**Comment by TomPrograms** [comment]
I'm sorry, I'm not quite sure what you are suggesting.

**Comment by exe19890522** [comment]
> I'm sorry, I'm not quite sure what you are suggesting.

i think you can format the db save data,not just all in one line.
