### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by gregbenner** [TomPrograms/stormdb#16]
I think a few things are missing, like .value() isn't in the documentation just under the browser example.

Also does the db have any search functionality?
```
[
  { name: 'tom' },
 { name: 'JIM' }
]
```
can you query the users list for the name JIM or you always return the whole db and filter in node/js
```js
const findOne = (name) => {
  return db
    .get("users")
    .value()
    .find((x) => x.name === name);
};```

**Comment by TomPrograms** [comment]
I'll add `.value()` to the main Readme.md at some point, thanks for pointing that out.

There currently is no search on the database at the moment, what you are doing is probably the best solution. I'll consider implementing a `.search()` in the future. Thanks for the feedback.
