### ISSUE TITLE
Allow for property accessors in the get() function.

### ISSUE THREAD

**Issue by LucAngevare** [TomPrograms/stormdb#17]
Currently, the `set()` function has the ability to set a value to a key without being in the actual object, by using property accessors (`object["key"]` or `object.key`). Say you have an object that looks like

`{"economy":{"people":{"Matt":100}}}`

You could use `db.set("economy.people.Jeff", 130)`. The `get()` function does not have the ability to use property accessors in this way, to get the value of Matt in this case, you'd need to use `db.get("economy").get("people").get("Matt")` which, when scaled up, can make the code really messy. My suggestion is to allow for property accessors in the `get()` functions, so you could do `db.get("economy.people.Matt")` so it would be way more intuitive as well to get variables.

For a key-based database like this one, it doesn't make sense and is kind of counter-intuitive to not allow for property accessors.

**Comment by TomPrograms** [comment]
I agree. I will work on this.

**Comment by TomPrograms** [comment]
I added this functionality for the `.get()` function with [this commit](https://github.com/TomPrograms/stormdb/commit/ca3f3a509810118e24ed3c0dc41b4adc2e670242). Thanks again for the suggestion.
