### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [TomPrograms/stormdb#2]
Hey, I saw this package from Reddit. 😄 It could use a types declaration file so that TypeScript developers can utilise TS while using this. If you'd like I can write a file for you.

**Comment by TomPrograms** [comment]
Sure, I'm not familiar with Typescript, but I would love a pull request. Thanks!

**Comment by TomPrograms** [comment]
If anyone could draft a Typescript declaration file that would be great!

**Comment by geopic** [comment]
Great, I'll get started on it now.

**Comment by TomPrograms** [comment]
@geopic Any word on this? I would like to get this in for the next  release.

**Comment by geopic** [comment]
I'll have it pushed by the end of today @TomPrograms.

**Comment by TomPrograms** [comment]
OK thanks a lot.
