### ISSUE TITLE
Is there any limitations to StormDB?

### ISSUE THREAD

**Issue by StriderRanger** [TomPrograms/stormdb#22]
Hi,

I've been looking for an embedded database that would be easily packaged with a nodejs, especially while using webpack, and StormDB was easily and perfectly integrated.
My main concern is to know if StormDB has any limitations regarding the database file size and performance (especially when the file db.stormdb grows in size). Would it be safe to use it in a production environment?

Thanks!

**Comment by TomPrograms** [comment]
It should be safe to use in a production environment (though I cannot make any guarantees). 

In terms of scaling, it depends. The core of StormDB is essentially just a JSON object with a nice StormDB wrapper around it which allows you to manipulate the data in nice ways. A modern system should be able to handle manipulating a very large JSON object with millions of properties and megabytes of data. The main speed limitation will come when you load a file or save to a file, which depends on the write/read speeds of the system. If you're loading/writing to a file on a HDD this could be quite slow with large amounts of data. I would have no problem in saying, if you keep saving and loading from a file/browser storage relatively rare, StormDB should be able to scale to millions of entries. The file size of the saved database will be the size of serialized (by defaulted JSON.strinify-ed) data. I personally would be comfortable using StormDB upto millions of entries and 10/15 megabytes of data, and the speed should be decent on a modern system. StormDB wouldn't scale properly to gigabytes of data.

Hope this helped a little.
