### ISSUE TITLE
Can't set more than one default value

### ISSUE THREAD

**Issue by Gitter499** [TomPrograms/stormdb#25]
Hi,

I am using StormDB for a project and I can't set more than one default value.

When I try `db.default({ users: [], questions: [] });`, and then try to push to the `questions` array, I get this error:

`You can only push to lists.`

Is this not supported or am I doing something wrong?

Edit: I decided to edit the stormdb file, and it worked that way. Altough I don't understand if I am missing something or there is a better way than that.

**Comment by TomPrograms** [comment]
Hi, this works for me. I think the issue may be that the default is only used when the database is completely empty. Maybe try the code with a completely empty database.

**Comment by Gitter499** [comment]
Hi, thanks for replying!

I've long finished the project, I ended up just modifying the stormDB file.

I'll try this if I need to use stormDB again.

Have a great day!
