### ISSUE TITLE
.push() replace other value

### ISSUE THREAD

**Issue by GladeCant** [TomPrograms/stormdb#26]
Hi,
I have, in my database :
```json
{
          "a": [
                    {
                         "b":"value"
                    }
          ]
}
``` 
and I want to add in the array "a" an object, like this :
```json
{
     "a": [
               {
                    "b":"value"
               },
               {
                    "c":"value"
               }
     ]
}
``` 

But when I do `db.get("a").push({ c: "value" }).save()`, that removes the first object and puts that one in its place ... So I have :
```json
{
     "a": [
               {
                    "c":"value"
               }
     ]
}
``` 

How to fix that, please ?
(Sorry if I make mistakes in the language : I'm not English ~)

**Comment by GladeCant** [comment]
Oh, sorry for the title. I wanted to change it to make it clearer, but I forgot.

**Comment by TomPrograms** [comment]
Hi. I'm sorry to hear this isn't working for you. I've setup this code [here ](https://tomprograms.github.io/stormdb/?code=db.set%28%2522a%2522%2C%2520%255B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2522b%2522%3A%2522value%2522%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%255D%29%250Adb.get%28%2522a%2522%29.push%28%257B%2520c%3A%2520%2522value%2522%2520%257D%29.save%28%29), which should be essentially the same as yours and it seems to work. Do you have other code which could be causing this?

**Comment by JamesBotterill** [comment]
I've ran into this same issue. 

I can probably expand on the issue. 

I start the db with a empty array like this: 

{
          "a": []
}

I push a new value for example db.get("a").push({ b: "value" }).save()

my database looks like this:

{
          "a": [
                    {
                         "b":"value"
                    }
          ]
}

I now want to push a further new value for example db.get("a").push({c: "value" }).save()

now when I look at the table the b value is missing and my table looks like this

{
          "a": [
                    {
                         "c":"value"
                    }
          ]
}

This is really confusing as I can't see why in my code this is happening.
