### ISSUE TITLE
inconsistent delete behavior

### ISSUE THREAD

**Issue by pachacamac** [TomPrograms/stormdb#27]
```JavaScript
import StormDB from 'stormdb';

const db = new StormDB(
  new StormDB.localFileEngine('./test.json', {
    serialize: data => JSON.stringify(data, null, 2),
  })
);

db.default({});
db.set("mylist", ["hello", "foobar", "world"]);
db.set("mymap", {0: "hello", 1: "foobar", 2: "world"});
db.save();
console.log(db.get("mylist.1").value());
console.log(db.get("mymap.1").value());
db.get("mylist.1").delete();
db.get("mymap.1").delete();
db.save();
console.log(db.get('mylist').value(), db.get('mymap').value());
```

The result will be:

```
foobar
foobar
[ 'hello', <1 empty item>, 'world' ] { '0': 'hello', '2': 'world' }
          ^^^^^^^^^^^^^^^
```

shouldn't the list element also be deleted?

**Comment by TomPrograms** [comment]
Hmmm... so this is because when you run the `.delete()` command, what is meant to be deleted is deleted using the `delete` keyword in Javascript. I wonder if this behaviour is preferable or whether we should change it so when deleting from a list, no empty item is left. Any input is welcome.

**Comment by pachacamac** [comment]
I'm also not 100% sure what would be better. What about adding an optional flag to the delete method? Something like `reindexArray=true` maybe?

**Comment by TomPrograms** [comment]
Alright I pushed an update, and the new behaviour is as following:

If you delete a value from a list, it will leave a null value in the place of the deleted data:

```js
db.get("key").get(1).delete();
// before: {'key': [1, 2, 3]}
// after: {'key2': [1, null, 3]}
```

```js
db.get("key").get(1).delete(true);
// before: {'key': [1, 2, 3]}
// after: {'key2': [1, 3]}
```

**Comment by TomPrograms** [comment]
I've just realised, this may require a change to the Typescript type declarations file. Since I have no experience with Typescript, but it seems you use Typescript, could you have a look at the type declarations file, and let me know if any changes are needed. Thanks.

**Comment by pachacamac** [comment]
Sure thing & thank you for the quick response. Line 10 of the index.d.ts file would become `delete(reindexLists: Boolean = false): void;`.

**Comment by TomPrograms** [comment]
Alright, thanks very much. I dropped the `=false` as my IDE was giving an error.
