### ISSUE TITLE
Issue retrieving information;

### ISSUE THREAD

**Issue by Magiclime** [TomPrograms/stormdb#28]
I am using StormDB for a project of mine,

I am trying to get it to find if a part of the database, Which looks like this;

{"users":["244173330431737866"]}

To find and make sure it exists, I want it to find "244173330431737866" and if it doesn't exist return false/true, So it can make a new entry within that number. I can't find a way to find this value within the db and with .get it doesn't seem to return true or false, Any help would be greatly appreciated.

**Comment by TomPrograms** [comment]
Hi, just get the value, and then use standard Javascript. This should work:

```
db.get("users").value().includes("244173330431737866");
```
