### ISSUE TITLE
Minor Type Adjustment to `StormDB.set`

### ISSUE THREAD

**Issue by xori** [TomPrograms/stormdb#31]
https://github.com/TomPrograms/stormdb/blob/fcb6d527e6b96df826d534f4b033edccf163b1ed/index.d.ts#L13
should be
```ts
set(key: any, value?: any): StormDB; 
```
so that your example works.
```ts
db.get("users")
  .get(0)
  .get("name")
  .set("jeff");
```

**Comment by TomPrograms** [comment]
Thanks. Done.
