### ISSUE TITLE
Any way to refresh the db?

### ISSUE THREAD

**Issue by GameBear64** [TomPrograms/stormdb#35]
I was wondering if there is a way to refresh the db kind of like *lowdb* has `.read()`?

Im making a simple web game and the db could change many times due to the multible users playing and im looking for a way to refresh the db during the game without having to refresh the whole server or seperate stuff in diferent modules.

LowDB has `db.read()` that works pretty well but I want to use storm instead.

**Comment by TomPrograms** [comment]
The database shouldn't need updating if the changes are made by one server in one file. If the changes are being made by multiple files, then factor out loading StormDB into a separate file, e.g.

Are these changes being made simultaneously by the same server? If so, have loading the database in a separate file, e.g.

```js
// db.js
const engine = new StormDB.localFileEngine("./db.stormdb");
module.exports = new StormDB(engine);
```

And then have each file that uses this database load `db.js`.

**Comment by GameBear64** [comment]
Would sill be a could feature but i see
Should be easy enough then, thanks a bunch!

**Comment by GameBear64** [comment]
## Made my own mod for anyone looking
Just add this to the stormdb.js file
```js
read() {
    this.state = this.engine.read()
}
```
And now you have db.read()
