### ISSUE TITLE
Impossible to access dot notation object keys

### ISSUE THREAD

**Issue by Townsheriff** [TomPrograms/stormdb#38]
Hey,

Thank you for your great project.

I"m in situation where I have emails as keys in an object and an email is structured as "example@inbox.com", storm db automatically splits this address in two pointers - "example@inbox" and "com". At the same time I can add an object to database with this notation (object key is not split in two parts).

An example to reproduce:
```
db.set("test", {"foo.bar": 1}); // creates {test: {"foo.bar": 1}}
db.get("test").get("foo.bar").set(2); // // sets property for {test: {foo: {bar: 2}}
```

As you can see I can put myself in a state where I cannot access it.

I propose an option in construction to disable dot notation.

Cheers,
Arturs

**Comment by Townsheriff** [comment]
Added a PR for this issue - https://github.com/TomPrograms/stormdb/pull/39

**Comment by Townsheriff** [comment]
If somebody needs to quick fix:
```
const clone = Object.assign(Object.create(Object.getPrototypeOf(this.db)), this.db);
clone.pointers = (key instanceof Array ? key : [key])    
clone.delete(false);
```

**Comment by TomPrograms** [comment]
Sorry for such a delay in my response to this. Your code looks good, and thanks for the PR. 

However, I wonder whether it might be better to add the option to an engine rather than the main StormDB object? Maybe since we already have options going in there?

**Comment by Townsheriff** [comment]
I think then we need to add them in 2 places then and perhaps in the future even to more places. I find engines as something that implements and interface aka adapters which do not know anything about how the lookup mapping works. 

But you are the author of the package, don't relay on me too much. :D

**Comment by TomPrograms** [comment]
I think two places might be redundant. I'll think about it, do some work, and then merge your PR. Thanks.

**Comment by TomPrograms** [comment]
Thanks again for the PR. I actually decided to move away from having this as a per-engine or per-instance option, but a per-function option, as I think disabling this will be relatively rare, and some may want to still be able to use dot notation in places, and disable it in others. 

We could add an extra option to turn this off by default across a whole instance, but for now, for simplicity, I think we will stick with this. To perform functions without dot notation, you can use:

```js
db.get("a.b", false);
db.set("a.b", "data", false);
```
