### ISSUE TITLE
Find Object

### ISSUE THREAD

**Issue by ricardoalexander** [TomPrograms/stormdb#40]
Hi,

Thank you for your great project. I wanted to ask on how to find a certain object by field (to update the data).

Example:
{"companies": [{"id": 5, "name": "Company A"}, {"id": 6, "name": "Company B"}]}

I wanted to update Company B by its id

Thanks

**Comment by xcraftarl** [comment]
Are you looking for something like this?
`
function updateCompanyNameByID(id, name) {
  db.companies.forEach((company) => {
    if (company.id === id) {
      company.name = name
    }
  })
}
`

**Comment by VikhyatModgil** [comment]
Are you looking for something like this?
```
function updateCompanyNameByID(id, name) {
  db.companies.forEach((company) => {
    if (company.id === id) {
      company.name = name
    }
  })
}
```

**Comment by ricardoalexander** [comment]
Hi @VikhyatModgil ,

I need to update the data using StormDB, not the array object.

Thanks

**Comment by TomPrograms** [comment]
Hi. There isn't currently any one function to do this in StormDB. To do this, grab the object from the database, change it with normal JS, then reinsert.

```js
// get companies
let companies = db.get("companies").value();

// update list with normal JS
let index = companies.findIndex((obj => obj.id == 1));
companies[index].name = "lol";

// reinsert list
db.set("companies", companies);
```
